###
GET http://localhost:3000/api/auth/api.json

###
POST http://localhost/api/auth/login
Content-Type: application/json

{
    "username": "khai.lv",
    "password": "2019",
    "deviceId": "xxxxx"
}

###
POST http://localhost/api/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyODAxNjY4Mjk3MzMyODg1NzM1IiwidXNlcm5hbWUiOiJraGFpLmx2IiwiZXhwIjoxNjU0NDE5MDEzLCJpYXQiOjE2NDg0MTkwMTN9.PwwPefSLjMI1Ctcev4_pFWoduxq-0_-S4i0K_Q7tZQYJKTa0aQPZXlHSkbrlz_t0nDVxjiVjrGydHhuCJZr5OtVfRbjE0aIf8Yvv_4FNOUBI7S4z5CJotuP23kTMRBAZ0vDL_WiLREPjqQcxeOqiDTxE4qkwGrI9687RXsNzYtU

{
    "refreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyODAxNjY4Mjk3MzMyODg1NzM1IiwidXNlcm5hbWUiOiJraGFpLmx2IiwiZXhwIjoxNjU0NDE5MDEzLCJpYXQiOjE2NDg0MTkwMTN9.PwwPefSLjMI1Ctcev4_pFWoduxq-0_-S4i0K_Q7tZQYJKTa0aQPZXlHSkbrlz_t0nDVxjiVjrGydHhuCJZr5OtVfRbjE0aIf8Yvv_4FNOUBI7S4z5CJotuP23kTMRBAZ0vDL_WiLREPjqQcxeOqiDTxE4qkwGrI9687RXsNzYtU",
    "ip": "1.52.204.129",
    "deviceId": "xxxxx"
}

###
POST http://localhost/api/auth/forgot-password
Content-Type: application/json

{
    "email": "roboticscm2018@gmail.com",
    "subject": "Lay lai mat khau",
    "html": "Vui long click vao link sau"
}

###
POST http://localhost/api/auth/reset-password
Content-Type: application/json

{
    "session": "57b03f9b-f6e1-4550-9e09-3e33626e36bb",
    "password": "2019",
    "ip": "xxx",
    "deviceDesc": "xxxxx"
}

###
POST http://localhost/api/auth/need-login
Content-Type: application/json

{
    "session": {
        "userId": "khai.lv"
    }
}

###
POST http://localhost/api/auth/need-admin-login
Content-Type: application/json

{
    "session": {
        "userId": "khai.lv"
    }
}