FROM golang:latest as builder
LABEL maintainer="Khai.lv <roboticscm2018@gmail.com>"
WORKDIR /src
COPY . .
RUN got get -u github.com/lib/pq
RUN go mod tidy
RUN CGO_ENABLED=0 go build -o /bin/linux_runner ./main.go


FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /app
COPY --from=builder /bin/linux_runner .
COPY common.config.json ./common.config.json
COPY keys/*.* ./keys/
EXPOSE 3002
ENTRYPOINT ["./linux_runner"] 